export enum Action {
    EDIT,
    REMOVE,
    NEW,
    CREATED,
    CHANGE,
    COMPLETE,
    APPROVE_DELETE,
    CONFIRM_OVERWRITE,
    SHOW_CONFIRM_MODAL,
    SHOW_ON_MAP,
    SET_COORDINATES,
    COORDINATES_DONE
}