export enum Action {
    EDIT,
    REMOVE,
    NEW,
    CREATED,
    CANCEL_EDIT,
    CHANGE,
    CHANGE_SINGLE_LOCATION,
    CHANGE_SINGLE_CATEGORY,
    NAVIGATION,
    COMPLETE,
    APPROVE_DELETE,
    CONFIRM_OVERWRITE,
    SHOW_CONFIRM_MODAL,
    SHOW_ON_MAP,
    SET_COORDINATES,
    COORDINATES_DONE
}